Develop
AlissonRP/Pokemom pull request #5
Opened 2022-02-12 18:48 UTC by AlissonRP

* Descrição das variáveis (corrigir pt se possível)
* Começo da análise descritiva,  a pallete tem  quantidade menor de cores disponíveis que a quantidade de tipos 1 (tentando resolver)
* Começo da descrição dos modelos

2022-02-12 20:31 UTC, VitorBSP commented
Todos os reviews que importam foram feitos, brincadeira! Irei revisar melhor após o jogo do colurado.

2022-02-13 00:42 UTC, VitorBSP requested changes

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +author: "Alisson Rosa e "
``
```suggestion
author: "Alisson Rosa e Vítor Pereira "
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +title: "title"
```suggestion
title: "Explorando a mística de Pokémon:  Previsão / Caracterização de Pokémons Lendários "
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +Pokémons são criaturas fictícias que pertencem ao universo da série de mesmo nome - Pokémon. Originalmente, a série foi criada como um jogo de videogame e, com a sua popularização, se espalhou para d
```suggestion
Pokémons são criaturas fictícias que pertencem ao universo da série de mesmo nome - Pokémon, são semelhantes a animais do mundo real, podendo viver em bandos ou individualmente, mas também podem ser inspirados em objetos inanimados como velas, sorvetes, chaveiro e outros instrumentos.  Originalmente, a série foi criada como um jogo de videogame e, com a sua popularização, se espalhou para diversos outros formatos, como séries de TV, filmes e livros.
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +A palavra pokémon é a contração de duas palavras em inglês: pocket, que significa bolso; e monster, que significa monstro. Assim, um pokémon é um "monstro de bolso", na tradução literal.
```suggestion
A palavra pokémon é a contração de duas palavras em inglês: pocket, que significa bolso; e monster, que significa monstro. Assim, um pokémon é um "monstro de bolso", na tradução literal, além de ser uma contração esse seria o nome original da série, devido ao lugar onde os Pokémons são armazenados:  as pokébolas, uma espécie de bola pequena para pode-los transportar com mais facilidade, sendo essas basicamente suas casas. Assim as criaturas poderiam descansar após suas batalhas, sendo essa sua principal função explorada no universo Pokémon, em que os monstrinhos lutam de acordo com habilidades da sua tipagem (Fogo, Água, Planta, Pedra, Elétrico, Voador, Lutador, Psíquico, Fantasma, entre outros.).  
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +Cada Pokémon tem seus próprios atributos, como HP (vida), Attack (Ataque), Defesa (Defense), Speed (velocidade) e outros mais especificos como:
```suggestion
Cada Pokémon tem seus próprios atributos, como HP (Vida), Attack (Ataque), Defesa (Defense), Speed (Velocidade) e outros mais especificos como:  
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +* **Generation** (geração): Uma Geração em Pokémon é um grupo de jogos separados de acordo com os Pokémon que estão incluídos nela. Cada geração possui novos Pokémon, ataques e habilidades que não ex
```suggestion
* **Generation** (geração): Uma Geração em Pokémon é um grupo de jogos separados de acordo com os Pokémon que estão incluídos nela. Cada geração possui novos Pokémons, ataques e habilidades que não existem nas gerações anteriores. Aqui portanto cada Pokémon tera sua respectiva geração, sendo tratata como uma variável de fator. 
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +* **Type** (Tipo): São classificações a que estão submetidos todos os Pokémon e técnicas (movimentos). A partir dos tipos, além de ser possível conhecer um pouco mais a natureza de cada Pokémon, é po
```suggestion
* **Type** (Tipo): São classificações a que estão submetidos todos os Pokémons e técnicas (movimentos). A partir dos tipos, além de ser possível conhecer um pouco mais a natureza de cada Pokémon, é possível também  elaborar estratégias de batalha. Isso porque cada tipo tem vantagens e desvantagens sobre outros tipos. Cada Pokémon pode pertencer a até dois tipos, sendo o primeiro deles o primário (Type 1) e o outro, o secundário (Type 2). Por outro lado, cada movimento tem só um tipo. Um Pokémon pode ter até quatro movimentos, mas elas não precisam ser do mesmo tipo que a criatura.
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +```{r}
```suggestion
```{r ref, E, fig.cap = "Frequência de Pokémons Lendários e Não Lendários por Tipo"}
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +         Generation = factor(Generation))
```suggestion
         Generation = factor(Generation), `Type 1` = factor(`Type 1`, unique(`Type 1`) )
         #Fiz esse ajuste para melhorar os gráfios para tornar ele mais compartivo, visto que de um lado a ordem dos tipos tá de um jeito, do outro lado tá de outro
```

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +Algoritmos de boosting atualmente são o estado da arte para dados estruturados, portanto é sempre bom ajustar algum deles
ESTADO DA ARTE, quero que discorra sobre.

2022-02-13 00:42 UTC, VitorBSP commented on relat.Rmd
> +Árvores de decisão são modelos que já existem a um certo tempo, apesar de terem uma grande vantagem em interpretabilidade são fracas em termos preditivos, assim a  idéia de Random Forest é combinar d
Ruim preditivamente? Achei que era ao contrário. Mas ainda sola reg log.

2022-02-13 01:02 UTC, VitorBSP requested changes

2022-02-13 01:02 UTC, VitorBSP commented on relat.Rmd
> +Vamos aqui estudar a quantidade de tipos por classificação dos Pokémons. O gráfico ref fornece um vislumbre
```suggestion
Vamos aqui estudar a quantidade de tipos por classificação dos Pokémons. O gráfico \@ref(fig:ref) fornece um vislumbre
```

2022-02-13 01:03 UTC, AlissonRP commented on relat.Rmd
> +Cada Pokémon tem seus próprios atributos, como HP (vida), Attack (Ataque), Defesa (Defense), Speed (velocidade) e outros mais especificos como:
```suggestion
Cada Pokémon tem seus próprios atributos, como HP (Vida), Attack (Ataque), Defense (Defesa), Speed (Velocidade) e outros mais especificos como:  
```

2022-02-13 01:09 UTC, merged